[package]
name = "sstv_2"
version = "0.2.1"
edition = "2024"
build = "build.rs"

[build-dependencies]
winres = "0.1"

[dependencies]
eframe = "0.32.0"
egui = "0.32.0"
hound = "3.5.1"
image = "0.25.6"
num-complex = "0.4.6"
rfd = "0.15.3"
